### ISSUE TITLE
configuration issue on mac (Getting pyembed flags from python-config: Could not build a python embedded interpreter)

### ISSUE THREAD

**Issue by yyf** [MTG/essentia#43]
After 
./waf configure --mode=release --with-python --with-cpptests --with-examples --with-vamp
## I got this

python executable ... differs from system...
...
Checking for library python2.7 in LIBPATH_PYEMBED: not found
Checking for library python2.7 in LIBDIR: not found
Checking for library python2.7 in python_LIBPL: not found
Checking for library python2.7 in $prefix/libs: not found
...
Getting pyembed flags from python-config: Could not build a python embedded interpreter
...
## The configuration failed

any pointer on how to resolve this? thanks.

**Comment by liumx10** [comment]
Maybe it is not the problem of this project. 
I got this problem when I use waf configure in another project. The error is same so I guess the solution may be the same. 
I check my build/config.log, and found that when g++ try to compile with command line option "-fstack-protector-strong", In fact, my g++ is 4.8 and does not support this command line option; So I replace this option in file /usr/lib/python2.7/plat-x86_64-linux-gnu/_sysconfigdata_nd.py to "-fstack-protector-all", which is supported by my g++. And then the problem is fixed.
I got information from this link. 

http://stackoverflow.com/questions/27182042/pip-error-unrecognized-command-line-option-fstack-protector-strong

**Comment by yyf** [comment]
I tried configuring essentia on a new machine (running 10.9.2) and got the same issue. I tried replacing -stdlib=libc++ with -stdlib=libstdc++ in wscript file, but still no luck. Any further pointer on this? thanks.

**Comment by dbogdanov** [comment]
@yyf which version of Essentia are you building?

**Comment by yyf** [comment]
@dbogdanov the Essentia 2.1 beta2 from the official release link.

**Comment by yyf** [comment]
@dbogdanov I fixed this by making homebrew-installed python default. However, Build Failed still, something to with yaml.
